layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 10
  exclude:
    archived: false
    forks: false
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: www.linkedin.com/in/jereddymanoj
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  website: www.manojjereddy.com
  # youtube: your_username

topics:
  - name: Machine Learning
    web_url: https://developers.google.com/machine-learning/crash-course
    image_url: https://coursera-course-photos.s3.amazonaws.com/8f/7afa60cbe911e8a233973e775a70ad/machine-learning-3.png?auto=format%2Ccompress&dpr=1

  - name: Data science
    web_url: https://datascience.berkeley.edu/about/what-is-data-science/
    image_url: https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTpYYt5kGMIEpcavNk4vw_TGqIrIKB5RX3NV99i61zSF3oOBSHV&usqp=CAU

  - name: Computer Vision
    web_url: https://techcrunch.com/2016/11/13/wtf-is-computer-vision/
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/800px-Cool_Kids_of_Death_Off_Festival_p_146-face_selected.jpg/300px-800px-Cool_Kids_of_Death_Off_Festival_p_146-face_selected.jpg

theme: jekyll-theme-hacker
